apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-ms-payment-gateway
  namespace: dev
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend-ms-payment-gateway
  template:
    metadata:
      labels:
        app: backend-ms-payment-gateway
        version: "1.01"
    spec:
      containers:
        - name: backend-ms-payment-gateway
          image: zebolhd/qa-backend-ms-payment-gateway:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: qa-secret
          ports:
            - containerPort: 5800

---
apiVersion: v1
kind: Service
metadata:
  name: backend-ms-payment-gateway
  namespace: dev
spec:
  selector:
    app: backend-ms-payment-gateway
  ports:
    - protocol: TCP
      port: 5800
      targetPort: 5800
      nodePort: 31800
  type: NodePort
